/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.User;

/**
 *
 * @author Hobby
 */
public class JFrameMain extends javax.swing.JFrame {

    /*
        Set up other JPanels that are displayed in the main frame
    */
    private JPanelLoginRegister loginPanel;
    private JPanelSearch searchPanel;
    private JPanelBasket basketPanel;
    private UnitTests.JPanelTest testPanel;
    
    
   //logged in user
    public Model.User loggedUser;
    
    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() {
        loginPanel = new JPanelLoginRegister();
        searchPanel = new JPanelSearch(this);
        basketPanel = new JPanelBasket();
        testPanel = new UnitTests.JPanelTest();
        
        loggedUser = new Model.User();
                        
        initComponents();
        
        jMenuTest.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jPanelMain = new javax.swing.JPanel();
        jLabelSplash = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemLoginRegister = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuActions = new javax.swing.JMenu();
        jMenuItemSearch = new javax.swing.JMenuItem();
        jMenuItemBasket = new javax.swing.JMenuItem();
        jMenuTest = new javax.swing.JMenu();
        jMenuItemTest = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trip Planner");
        setName("frameMain"); // NOI18N

        jPanelMain.setLayout(new java.awt.CardLayout());

        jLabelSplash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSplash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/On-bike-from-Laki-to-Landmannalaugar-IMB71.jpg"))); // NOI18N

        jMenuFile.setText("File");

        jMenuItemLoginRegister.setText("Login/Register");
        jMenuItemLoginRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoginRegisterActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemLoginRegister);

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar1.add(jMenuFile);

        jMenuActions.setText("Actions");

        jMenuItemSearch.setText("Search");
        jMenuItemSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSearchActionPerformed(evt);
            }
        });
        jMenuActions.add(jMenuItemSearch);

        jMenuItemBasket.setText("Basket");
        jMenuItemBasket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBasketActionPerformed(evt);
            }
        });
        jMenuActions.add(jMenuItemBasket);

        jMenuBar1.add(jMenuActions);

        jMenuTest.setText("TestArea");

        jMenuItemTest.setText("Test Window");
        jMenuItemTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTestActionPerformed(evt);
            }
        });
        jMenuTest.add(jMenuItemTest);

        jMenuBar1.add(jMenuTest);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelSplash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelSplash, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemLoginRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoginRegisterActionPerformed
        clearPanel();
        jPanelMain.add(loginPanel);
        repaint();
    }//GEN-LAST:event_jMenuItemLoginRegisterActionPerformed

    private void jMenuItemSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSearchActionPerformed
        clearPanel();
        jPanelMain.add(searchPanel);
        repaint();
    }//GEN-LAST:event_jMenuItemSearchActionPerformed

    private void jMenuItemBasketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBasketActionPerformed
        clearPanel();
        jPanelMain.add(basketPanel);        
        repaint();        
    }//GEN-LAST:event_jMenuItemBasketActionPerformed

    private void jMenuItemTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTestActionPerformed
        clearPanel();
        jPanelMain.add(testPanel);        
        repaint();  
    }//GEN-LAST:event_jMenuItemTestActionPerformed

    //moving to basket window, passing in a basket with content
    public void toBasket(Model.Basket basket){
        clearPanel();
        basketPanel = new JPanelBasket(basket);
        jPanelMain.add(basketPanel);        
        repaint();  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMain().setVisible(true);
            }
        });
    }

    /*
        clears the jPanelMain
    */
    private void clearPanel(){
        jLabelSplash.setVisible(false);
        jPanelMain.setVisible(false);
        jPanelMain.removeAll();
        jPanelMain.invalidate();
        jPanelMain.repaint();
        jPanelMain.setVisible(true);                 
    }
    
    public User getLoggedUser(){
        return this.loggedUser;
    }
    
    public void setLoggedUser(User user){
        this.loggedUser = user;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelSplash;
    private javax.swing.JMenu jMenuActions;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemBasket;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemLoginRegister;
    private javax.swing.JMenuItem jMenuItemSearch;
    private javax.swing.JMenuItem jMenuItemTest;
    private javax.swing.JMenu jMenuTest;
    private javax.swing.JPanel jPanelMain;
    // End of variables declaration//GEN-END:variables
}
