/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Hobby
 */
public class JFrameMain extends javax.swing.JFrame {

    /*
        Set up other JPanels that are displayed in the main frame
    */
    private JPanelLoginRegister loginPanel;
    private JPanelSearch searchPanel;
    
    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() {
        loginPanel = new JPanelLoginRegister();
        searchPanel = new JPanelSearch();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jPanelMain = new javax.swing.JPanel();
        jLabelSplash = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemLoginRegister = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuSearch = new javax.swing.JMenu();
        jMenuItemSearch = new javax.swing.JMenuItem();
        jMenuBasket = new javax.swing.JMenu();
        jMenuItemBasketCurrent = new javax.swing.JMenuItem();
        jMenuItemBasketPrevious = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trip Planner");
        setName("frameMain"); // NOI18N

        jPanelMain.setLayout(new java.awt.CardLayout());

        jLabelSplash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSplash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/On-bike-from-Laki-to-Landmannalaugar-IMB71.jpg"))); // NOI18N

        jMenuFile.setText("File");

        jMenuItemLoginRegister.setText("Login/Register");
        jMenuItemLoginRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoginRegisterActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemLoginRegister);

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar1.add(jMenuFile);

        jMenuSearch.setText("Search");

        jMenuItemSearch.setText("Search");
        jMenuItemSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSearchActionPerformed(evt);
            }
        });
        jMenuSearch.add(jMenuItemSearch);

        jMenuBar1.add(jMenuSearch);

        jMenuBasket.setText("Basket");

        jMenuItemBasketCurrent.setText("Current");
        jMenuBasket.add(jMenuItemBasketCurrent);

        jMenuItemBasketPrevious.setText("Previous");
        jMenuBasket.add(jMenuItemBasketPrevious);

        jMenuBar1.add(jMenuBasket);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addComponent(jLabelSplash, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelSplash, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemLoginRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoginRegisterActionPerformed
        clearPanel();
        jPanelMain.add(loginPanel);
        repaint();
    }//GEN-LAST:event_jMenuItemLoginRegisterActionPerformed

    private void jMenuItemSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSearchActionPerformed
        clearPanel();
        jPanelMain.add(searchPanel);
        repaint();
    }//GEN-LAST:event_jMenuItemSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMain().setVisible(true);
            }
        });
    }

    /*
        clears the jPanelMain
    */
    private void clearPanel(){
        jLabelSplash.setVisible(false);
        jPanelMain.setVisible(false);
        jPanelMain.removeAll();
        jPanelMain.invalidate();
        jPanelMain.repaint();
        jPanelMain.setVisible(true);                 
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelSplash;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBasket;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemBasketCurrent;
    private javax.swing.JMenuItem jMenuItemBasketPrevious;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemLoginRegister;
    private javax.swing.JMenuItem jMenuItemSearch;
    private javax.swing.JMenu jMenuSearch;
    private javax.swing.JPanel jPanelMain;
    // End of variables declaration//GEN-END:variables
}
