/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import model.Flight;
import Controller.Search;
import Model.Basket;
import Model.DEPRECIATED_Preference;
import Model.*;
import Model.User;
import ViewModel.SearchVM;
import hotel3h.Hotel;
import java.sql.Date;
import java.time.LocalDate;
import java.util.List;
import javax.swing.DefaultListModel;
import model.Trip;

/**
 *
 * @author Hobby
 */
public class JPanelSearch extends javax.swing.JPanel {

    User user;
    Basket basket;
    Basket selectedBasket;

    private Controller.Search search;
    private JFrameMain parent;

    /**
     * Creates new form JPanelSearch, fake user generated with id of -99, used
     * for testing
     */
    public JPanelSearch(JFrameMain parent) {
        this.parent = parent;
        
        initComponents();

        this.setupConfig();
        user = new User(-99);

        this.jLabel4.setVisible(false);
        this.jFormattedTextFieldMinimumPrice.setVisible(false);
        this.jLabel5.setVisible(false);
        this.jFormattedTextFieldMaximumPrice.setVisible(false);
    }

    /**
     * *
     * Creates new form JPanelSearch, searches for user by id on creation
     *
     * @param userID id of user that is searched for
     */
    public JPanelSearch(int userID) {
        initComponents();

        this.setupConfig();
        user = new User(userID);
        
        this.jLabel4.setVisible(false);
        this.jFormattedTextFieldMinimumPrice.setVisible(false);
        this.jLabel5.setVisible(false);
        this.jFormattedTextFieldMaximumPrice.setVisible(false);

    }

    /**
     * *
     * Creates new form JPanelSearch,created with selected user
     *
     * @param user selected user
     */
    public JPanelSearch(User user) {
        initComponents();

        this.setupConfig();
        this.user = user;

        this.jLabel4.setVisible(false);
        this.jFormattedTextFieldMinimumPrice.setVisible(false);
        this.jLabel5.setVisible(false);
        this.jFormattedTextFieldMaximumPrice.setVisible(false);
        
    }

    /**
     * *
     * user generated configuration for JPanelSearch
     */
    private void setupConfig() {
        search = new Search();

        Date curDate = Date.valueOf(LocalDate.now());
        String curDateS = curDate.toString();
        this.jFormattedTextFieldDateStart.setText(curDateS);
        this.jFormattedTextFieldDateEnd.setText(curDateS);

        basket = new Basket();
        selectedBasket = new Basket();
        UpdateSelectPanels();
    }

    private void UpdateSelectPanels() {
        this.UpdateSelectPanels(this.basket);
    }
    
    public Basket getSelectedBasket(){
        return(this.selectedBasket);
    }

    private void UpdateSelectPanels(Basket basket) {
        List<Flight> flights = basket.getFlights();
        DefaultListModel<String> flightsModel = new DefaultListModel<>();
        if (flights != null) {
            for (Flight flight : flights) {
                flightsModel.addElement(flight.getAirline() + ", " + flight.getDeparture_from() + ", " + flight.getArrival_to() + ", " + flight.getTicket_price());
            }
        }
        this.jListSearchResultsFlights.setModel(flightsModel);

        List<Hotel> hotels = basket.getHotels();
        DefaultListModel<String> hotelsModel = new DefaultListModel<>();
        if (hotels != null) {
            for (Hotel hotel : hotels) {
                hotelsModel.addElement(hotel.getName() + ", " + hotel.getMinPrice()*100);
            }
        }
        this.jListSearchResultsHotels.setModel(hotelsModel);

        List<Trip> trips = basket.getTrips();
        DefaultListModel<String> tripsModel = new DefaultListModel<>();
        if (trips != null) {
            for (Trip trip : trips) {
                tripsModel.addElement(trip.getName() + ", " + trip.getPrice());
            }
        }

        this.jListSearchResultsTrips.setModel(tripsModel);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jCheckBoxTwoWay = new javax.swing.JCheckBox();
        jCheckBoxHotels = new javax.swing.JCheckBox();
        jCheckBoxTrips = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextFieldDateStart = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDateEnd = new javax.swing.JFormattedTextField();
        jFormattedTextFieldMinimumPrice = new javax.swing.JFormattedTextField();
        jFormattedTextFieldMaximumPrice = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListSearchResultsFlights = new javax.swing.JList<>();
        jButtonToBasket = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextFieldNumberOfCustomers = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListSearchResultsTrips = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListSearchResultsHotels = new javax.swing.JList<>();
        jComboBoxFlightTo = new javax.swing.JComboBox<>();
        jComboBoxFlightFrom = new javax.swing.JComboBox<>();
        jLabelFrom = new javax.swing.JLabel();
        jLabelTo = new javax.swing.JLabel();
        jLabelFlight = new javax.swing.JLabel();
        jCheckBoxFlights = new javax.swing.JCheckBox();

        jCheckBoxTwoWay.setSelected(true);
        jCheckBoxTwoWay.setText("Two Way");
        jCheckBoxTwoWay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTwoWayActionPerformed(evt);
            }
        });

        jCheckBoxHotels.setSelected(true);
        jCheckBoxHotels.setText("Hotels");
        jCheckBoxHotels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxHotelsActionPerformed(evt);
            }
        });

        jCheckBoxTrips.setSelected(true);
        jCheckBoxTrips.setText("Trips");

        jLabel1.setText("Search For:");

        jLabel2.setText("Date Start");

        jLabel3.setText("Date End");

        jLabel4.setText("Minimum Price");

        jLabel5.setText("Maximum Price");

        jFormattedTextFieldDateStart.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        jFormattedTextFieldDateStart.setToolTipText("yyyy-MM-dd");

        jFormattedTextFieldDateEnd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        jFormattedTextFieldDateEnd.setToolTipText("yyyy-MM-dd");

        jFormattedTextFieldMinimumPrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextFieldMinimumPrice.setText("0.0");

        jFormattedTextFieldMaximumPrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextFieldMaximumPrice.setText("0.0");
        jFormattedTextFieldMaximumPrice.setToolTipText("");

        jLabel6.setText("Currency Type");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ISK", "EUR", "GBP", "$" }));

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jListSearchResultsFlights.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListSearchResultsFlights);

        jButtonToBasket.setText("Add Selected To Basket");
        jButtonToBasket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonToBasketActionPerformed(evt);
            }
        });

        jLabel7.setText("# of customers");
        jLabel7.setToolTipText("");

        jFormattedTextFieldNumberOfCustomers.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextFieldNumberOfCustomers.setText("0");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Capital area", "Eastern region", "Western region", "Northern region", "Southern region", "Highlands of Iceland" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Trip Area");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Golden Circle", "Horse Trips", "Volcano", "Glaciers", "Beer Trips", "Food Trips" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel9.setText("Trip Type");
        jLabel9.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jListSearchResultsTrips.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListSearchResultsTrips);

        jListSearchResultsHotels.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListSearchResultsHotels);

        jComboBoxFlightTo.setMaximumRowCount(4);
        jComboBoxFlightTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Akureyri", "Reykjavík", "Vestmannaeyjar", "Ísafjörður", " " }));
        jComboBoxFlightTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFlightToActionPerformed(evt);
            }
        });

        jComboBoxFlightFrom.setMaximumRowCount(4);
        jComboBoxFlightFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reykjavík", "Vestmannaeyjar", "Ísafjörður", "Akureyri", " " }));
        jComboBoxFlightFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFlightFromActionPerformed(evt);
            }
        });

        jLabelFrom.setText("From");

        jLabelTo.setText("To");

        jLabelFlight.setText("Flight");

        jCheckBoxFlights.setSelected(true);
        jCheckBoxFlights.setText("Flights");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBoxTrips)
                                        .addGap(8, 8, 8))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCheckBoxHotels)
                                        .addComponent(jCheckBoxFlights)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabelFlight)
                                        .addGap(41, 41, 41))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBoxFlightFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelFrom)
                                        .addComponent(jCheckBoxTwoWay)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxFlightTo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTo))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jFormattedTextFieldNumberOfCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jFormattedTextFieldDateEnd)
                                            .addComponent(jFormattedTextFieldDateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jFormattedTextFieldMinimumPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jFormattedTextFieldMaximumPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jButtonSearch, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jButtonToBasket)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelFlight, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jCheckBoxFlights)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBoxHotels)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBoxTrips)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelFrom)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxFlightFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelTo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxFlightTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxTwoWay)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jFormattedTextFieldNumberOfCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jFormattedTextFieldDateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldDateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldMinimumPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldMaximumPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSearch)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonToBasket)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxHotelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxHotelsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxHotelsActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed

        ViewModel.SearchVM vm = new SearchVM();
        vm.setUser(user);

        String minDate = this.jFormattedTextFieldDateEnd.getText();
        vm.setDateStart(Date.valueOf(minDate));
        String maxDate = this.jFormattedTextFieldDateStart.getText();
        vm.setDateEnd(Date.valueOf(maxDate));

        String minPrice = this.jFormattedTextFieldMinimumPrice.getText();
        vm.setPriceRangeMin(Double.valueOf(minPrice));
        String maxPrice = this.jFormattedTextFieldMaximumPrice.getText();
        vm.setPriceRangeMax(Double.valueOf(maxPrice));

        String numberOfCustomers = this.jFormattedTextFieldNumberOfCustomers.getText();
        vm.setPeople(Integer.valueOf(numberOfCustomers));

        String curency = this.jComboBox1.getItemAt(this.jComboBox1.getSelectedIndex());
        vm.setCurrencyType(curency);
        
        String fromWhere = this.jComboBoxFlightFrom.getItemAt(this.jComboBoxFlightFrom.getSelectedIndex());
        vm.setFromWhere(fromWhere);
        String toWhere = this.jComboBoxFlightTo.getItemAt(this.jComboBoxFlightTo.getSelectedIndex());
        vm.setToWhere(toWhere);

        Boolean searchFlights = this.jCheckBoxFlights.isSelected();
        Boolean searchHotels = this.jCheckBoxHotels.isSelected();
        Boolean searchTrips = this.jCheckBoxTrips.isSelected();
        Boolean twoWay = this.jCheckBoxTwoWay.isSelected();
        vm.setTwoWay(twoWay);
        

        String area = this.jComboBox2.getItemAt(this.jComboBox2.getSelectedIndex());
        vm.setArea(area);

        String prefrence = this.jComboBox3.getItemAt(this.jComboBox3.getSelectedIndex());
        vm.setPref(prefrence);

        //search.SearchAll(dateEnd, day, priceRangeMax, priceRangeMax, currencyType, PROPERTIES, preferences, true, true, true);
        basket = search.SearchAll(vm, searchFlights, searchHotels, searchTrips);
        UpdateSelectPanels();
        
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonToBasketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonToBasketActionPerformed
        int[] flightIndex = this.jListSearchResultsFlights.getSelectedIndices();
        int[] hotelIndex  = this.jListSearchResultsHotels.getSelectedIndices();
        int[] tripIndex   = this.jListSearchResultsTrips.getSelectedIndices();
        for(int t=0;t<tripIndex.length;t++){
            selectedBasket.addTrip(basket.getTrip(tripIndex[t]));
        }
        for(int h=0;h<hotelIndex.length;h++){
            selectedBasket.addHotel(basket.getHotel(hotelIndex[h]));
        }
        for(int f=0;f<flightIndex.length;f++){
            selectedBasket.addFlight(basket.getFlight(flightIndex[f]));
        }
        
        parent.toBasket(selectedBasket);
    }//GEN-LAST:event_jButtonToBasketActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBoxFlightToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFlightToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFlightToActionPerformed

    private void jComboBoxFlightFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFlightFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFlightFromActionPerformed

    private void jCheckBoxTwoWayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTwoWayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTwoWayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonToBasket;
    private javax.swing.JCheckBox jCheckBoxFlights;
    private javax.swing.JCheckBox jCheckBoxHotels;
    private javax.swing.JCheckBox jCheckBoxTrips;
    private javax.swing.JCheckBox jCheckBoxTwoWay;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBoxFlightFrom;
    private javax.swing.JComboBox<String> jComboBoxFlightTo;
    private javax.swing.JFormattedTextField jFormattedTextFieldDateEnd;
    private javax.swing.JFormattedTextField jFormattedTextFieldDateStart;
    private javax.swing.JFormattedTextField jFormattedTextFieldMaximumPrice;
    private javax.swing.JFormattedTextField jFormattedTextFieldMinimumPrice;
    private javax.swing.JFormattedTextField jFormattedTextFieldNumberOfCustomers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFlight;
    private javax.swing.JLabel jLabelFrom;
    private javax.swing.JLabel jLabelTo;
    private javax.swing.JList<String> jListSearchResultsFlights;
    private javax.swing.JList<String> jListSearchResultsHotels;
    private javax.swing.JList<String> jListSearchResultsTrips;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
