/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UnitTests;

import Controller.DBC;

/**
 *
 * @author Hobby
 */
public class JPanelTest extends javax.swing.JPanel {

    /**
     * Creates new form JPanelTest
     */
    public JPanelTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelQueryResult = new javax.swing.JLabel();
        jButtonQueryUserId = new javax.swing.JButton();
        jTextFieldInput1 = new javax.swing.JTextField();

        jLabelQueryResult.setText("Query Result");

        jButtonQueryUserId.setText("Get User Id");
        jButtonQueryUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQueryUserIdActionPerformed(evt);
            }
        });

        jTextFieldInput1.setText("User Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonQueryUserId)
                        .addGap(28, 28, 28)
                        .addComponent(jTextFieldInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelQueryResult))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonQueryUserId)
                    .addComponent(jTextFieldInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabelQueryResult)
                .addContainerGap(208, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonQueryUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQueryUserIdActionPerformed
        String str = this.jTextFieldInput1.getText();
        int n = DBC.getUserId(str);
        this.jLabelQueryResult.setText(String.valueOf(n));
    }//GEN-LAST:event_jButtonQueryUserIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonQueryUserId;
    private javax.swing.JLabel jLabelQueryResult;
    private javax.swing.JTextField jTextFieldInput1;
    // End of variables declaration//GEN-END:variables
}
